// This List is for City and Municipal
var citymunicipal = [
    "Select City",
    "Bacolod City",
    "Bago City",
    "Binalbagan",
    "Calatrava",
    "Cadiz City",
    "Candoni",
    "Cauayan",
    "EB Magalona",
    "Escalante City",
    "Himamaylan City",
    "Hinigaran",
    "Hinoba-an",
    "Ilog",
    "Isabela",
    "Kabankalan City",
    "La Carlota City",
    "La Castellana",
    "Manapla",
    "Moises Padilla",
    "Murcia",
    "Pontevedra",
    "Pulupandan",
    "Salvador Benedicto",
    "Sagay City",
    "San Carlos City",
    "San Enrique",
    "Silay City",
    "Sipalay City",
    "Talisay City",
    "Toboso",
    "Valladolid",
    "Victorias City"
];

//  this list is for Bacolod City
var bacolodCity = [
    "Alangilan",
    "Alijis",
    "Banago",
    "Barangay 1 (Poblacion)",
    "Barangay 2 (Poblacion)",
    "Barangay 3 (Poblacion)",
    "Barangay 4 (Poblacion)",
    "Barangay 5 (Poblacion)",
    "Barangay 6 (Poblacion)",
    "Barangay 7 (Poblacion)",
    "Barangay 8 (Poblacion)",
    "Barangay 9 (Poblacion)",
    "Barangay 10 (Poblacion)",
    "Barangay 11 (Poblacion)",
    "Barangay 12 (Poblacion)",
    "Barangay 13 (Poblacion)",
    "Barangay 14 (Poblacion)",
    "Barangay 15 (Poblacion)",
    "Barangay 16 (Poblacion)",
    "Barangay 17 (Poblacion)",
    "Barangay 18 (Poblacion)",
    "Barangay 19 (Poblacion)",
    "Barangay 20 (Poblacion)",
    "Barangay 21 (Poblacion)",
    "Barangay 22 (Poblacion)",
    "Barangay 23 (Poblacion)",
    "Barangay 24 (Poblacion)",
    "Barangay 25 (Poblacion)",
    "Barangay 26 (Poblacion)",
    "Barangay 27 (Poblacion)",
    "Barangay 28 (Poblacion)",
    "Barangay 29 (Poblacion)",
    "Barangay 30 (Poblacion)",
    "Barangay 31 (Poblacion)",
    "Barangay 32 (Poblacion)",
    "Barangay 33 (Poblacion)",
    "Barangay 34 (Poblacion)",
    "Barangay 35 (Poblacion)",
    "Barangay 36 (Poblacion)",
    "Barangay 37 (Poblacion)",
    "Barangay 38 (Poblacion)",
    "Barangay 39 (Poblacion)",
    "Barangay 40 (Poblacion)",
    "Barangay 41 (Poblacion",
    "Bata",
    "Cabug",
    "Estefania",
    "Felisa",
    "Granada",
    "Handumanan",
    "Mandalagan",
    "Mansilingan",
    "Montevista",
    "Pahanocoy",
    "Punta Taytay",
    "Singcang-Airport",
    "Sum-ag",
    "Taculing",
    "Tangub",
    "Villamonte",
    "Vista Alegre",
];
var HimamaylanBrgy = [
    "Aguisan",
    "Buenavista",
    "Barangay I (Poblacion)",
    "Barangay II (Poblacion)",
    "Barangay III (Poblacion)",
    "Barangay IV (Poblacion)",
    "Cabadiangan",
    "Cabanbanan",
    "Carabalan",
    "Caradio-an",
    "Libacao",
    "Mambagaton",
    "Nabali-an",
    "Mahalang",
    "San Antonio",
    "Sara-et",
    "Su-ay",
    "Talaban",
    "To-oy",
];

var BagoCity = [
    "Abuanan",
    "Alianza",
    "Atipuluan",
    "Bacong-Montilla",
    "Bagroy",
    "Balingasag",
    "Binubuhan",
    "Busay",
    "Calumangan",
    "Caridad",
    "Don Jorge L. Araneta",
    "Dulao",
    "Ilijan",
    "Lag-Asan",
    "Ma-ao",
    "Mailum",
    "Malingin",
    "Napoles",
    "Pacol",
    "Poblacion",
    "Sagasa",
    "Tabunan",
    "Taloc",
    "Sampinit"
];
// Binalbagan
var Binalbagan = [
    "Amontay",
    "Bagroy",
    "Binalbagan Proper",
    "Bi-ao",
    "Canmoros",
    "Enclaro",
    "Marina",
    "Pagla-um (Poblacion)",
    "Payao (formerly Soledad)",
    "Progreso",
    "Remedios",
    "San Jose",
    "San Juan",
    "San Pedro (Poblacion)",
    "San Teodoro",
    "San Vicente",
    "Santo Rosario (Poblacion)",
    "Santol"
];
var Calatrava = [
    "Agpangi",
    "Ani-e",
    "Bagacay",
    "Bantayanon",
    "Buenavista",
    "Cabungahan",
    "Calampisawan",
    "Cambayobo",
    "Castellano",
    "Cruz",
    "Dolis",
    "Hilub-Ang",
    "Hinab-Ongan",
    "Ilaya",
    "Laga-an",
    "Lalong",
    "Lemery",
    "Lipat-on",
    "Lo-ok (Poblacion)",
    "Ma-aslob",
    "Macasilao",
    "Malanog",
    "Malatas",
    "Marcelo",
    "Mina-utok",
    "Menchaca",
    "Minapasuk",
    "Mahilum",
    "Paghumayan",
    "Pantao",
    "Patun-an",
    "Pinocutan",
    "Refugio",
    "San Benito",
    "San Isidro",
    "Suba (Poblacion)",
    "Telim",
    "Tigbao",
    "Tigbon",
    "Winaswasan"
];
var CadizCity = [
    "Andres Bonifacio",
    "Banquerohan",
    "Barangay 1 Pob. (Zone 1)",
    "Barangay 2 Pob. (Zone 2)",
    "Barangay 3 Pob. (Zone 3)",
    "Barangay 4 Pob. (Zone 4)",
    "Barangay 5 Pob. (Zone 5)",
    "Barangay 6 Pob. (Zone 6)",
    "Burgos",
    "Cabahug",
    "Cadiz Viejo",
    "Caduha-an",
    "Celestino Villacin",
    "Daga",
    "V. F. Gustilo",
    "Jerusalem",
    "Luna",
    "Mabini",
    "Magsaysay",
    "Sicaba",
    "Tiglawigan",
    "Tinampa-an"
];

var Candoni = [
    "Agboy",
    "Banga",
    "Cabia - an",
    "Caningay",
    "Gatuslao",
    "Haba",
    "Payauan",
    "Poblacion East",
    "Poblacion West"
];

var Cauayan = [
    "Abaca",
    "Baclao",
    "Basak",
    "Bulata",
    "Caliling",
    "Camalanda-an",
    "Camindangan",
    "Elihan",
    "Guiljungan",
    "Inayawan",
    "Isio",
    "Linaon",
    "Lumbia",
    "Mambugsay",
    "Man-uling",
    "Masaling",
    "Molobolo",
    "Poblacion",
    "Sura",
    "Talacdan",
    "Tambad",
    "Tiling",
    "Tomina",
    "Tuyom",
    "Yaoyao"
];
var EBMagalona = [
    "Alacaygan",
    "Alicante",
    "Poblacion I (Barangay 1)",
    "Poblacion II (Barangay 2)",
    "Poblacion III (Barangay 3)",
    "Batea",
    "Consing",
    "Cudangdang",
    "Damgo",
    "Gahit",
    "Canlusong",
    "Latasan",
    "Madalag",
    "Manta-angan",
    "Nanca",
    "Pasil",
    "San Isidro",
    "San Jose",
    "Santo Niño",
    "Tabigue",
    "Tanza",
    "Tuburan",
    "Tomongtong"
];

var Escalante = [
    "Alimango",
    "Balintawak",
    "Binaguiohan",
    "Buenavista",
    "Cervantes",
    "Dian-ay",
    "Hda. Fe",
    "Japitan",
    "Jonobjonob",
    "Langub",
    "Libertad",
    "Mabini",
    "Magsaysay",
    "Malasibog",
    "Old Poblacion",
    "Paitan",
    "Pinapugasan",
    "Rizal",
    "Tamlang",
    "Udtongan",
    "Washington"
];
var Hinigaran = [
    "Anahaw",
    "Aranda",
    "Baga-as",
    "Barangay I (Poblacion)",
    "Barangay II (Poblacion)",
    "Barangay III (Poblacion)",
    "Barangay IV (Poblacion)",
    "Bato",
    "Calapi",
    "Camalobalo",
    "Camba-og",
    "Cambugsa",
    "Candumarao",
    "Gargato",
    "Himaya",
    "Miranda",
    "Nanunga",
    "Narauis",
    "Palayog",
    "Paticui",
    "Pilar",
    "Quiwi",
    "Tagda",
    "Tuguis"
];
var Hinobaan = [
    "Alim",
    "Asia",
    "Bacuyangan",
    "Barangay I (Poblacion)",
    "Barangay II (Poblacion)",
    "Bulwangan",
    "Culipapa",
    "Damutan",
    "Daug",
    "Po-ok",
    "San Rafael",
    "Sangke",
    "Talacagay"
];
var Ilog = [
    "Andulauan",
    "Balicotoc",
    "Bocana",
    "Calubang",
    "Canlamay",
    "Consuelo",
    "Dancalan",
    "Delicioso",
    "Galicia",
    "Manalad",
    "Pinggot",
    "Barangay I (Poblacion)",
    "Barangay II (Poblacion)",
    "Tabu",
    "Vista Alegre"
]
var Isabela = [
    "Amin",
    "Banogbanog",
    "Bulad",
    "Bungahin",
    "Cabcab",
    "Camangcamang",
    "Camp Clark",
    "Cansalongon",
    "Guintubhan",
    "Libas",
    "Limalima",
    "Makilignit",
    "Mansablay",
    "Maytubig",
    "Panaquiao",
    "Barangay 1 (Poblacion)",
    "Barangay 2 (Poblacion)",
    "Barangay 3 (Poblacion)",
    "Barangay 4 (Poblacion)",
    "Barangay 5 (Poblacion)",
    "Barangay 6 (Poblacion)",
    "Barangay 7 (Poblacion)",
    "Barangay 8 (Poblacion)",
    "Barangay 9 (Poblacion)",
    "Riverside",
    "Rumirang",
    "San Agustin",
    "Sebucawan",
    "Sikatuna",
    "Tinongan"
];
var KabankalanCIty = [
    "Bantayan",
    "Binicuil",
    "Camansi",
    "Camingawan",
    "Camugao",
    "Carol-an",
    "Daan Banua",
    "Hilamonan",
    "Inapoy",
    "Linao",
    "Locotan",
    "Magballo",
    "Oringao",
    "Orong",
    "Pinaguinpinan",
    "Barangay 5 (Poblacion)",
    "Barangay 6 (Poblacion)",
    "Barangay 7 (Poblacion)",
    "Barangay 8 (Poblacion)",
    "Barangay 9 (Poblacion)",
    "Barangay 1 (Poblacion)",
    "Barangay 2 (Poblacion)",
    "Barangay 3 (Poblacion)",
    "Barangay 4 (Poblacion)",
    "Salong",
    "Tabugon",
    "Tagoc",
    "Tagukon",
    "Talubangi",
    "Tampalon",
    "Tan-Awan",
    "Tapi"
];
var LaCarlota = [
    "Ara-al",
    "Ayungon",
    "Balabag",
    "Batuan",
    "Consuelo",
    "Cubay",
    "Haguimit",
    "La Granja",
    "Nagasi",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "San Miguel",
    "Yubo"
];
var LaCastellana = [
    "Biaknabato",
    "Cabacungan",
    "Cabagnaan",
    "Camandag",
    "Lalagsan",
    "Manghanoy",
    "Mansalanao",
    "Masulog",
    "Nato",
    "Puso",
    "Robles (Poblacion)",
    "Sag-Ang",
    "Talaptap"
];
var Manapla = [
    "Chambéry",
    "Barangay I (Poblacion)",
    "Barangay I-A (Poblacion)",
    "Barangay I-B (Poblacion)",
    "Barangay II (Poblacion)",
    "Barangay II-A (Poblacion)",
    "Punta Mesa",
    "Punta Salong",
    "Purisima",
    "San Pablo",
    "Santa Teresa",
    "Tortosa"
];

var MoisisPaddilla = [
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Crossing Magallon",
    "Guinpana-an",
    "Inolingan",
    "Macagahay",
    "Magallon Cadre",
    "Montilla",
    "Odiong",
    "Quintin Remo"
];
var Murcia = [
    'Abo-abo',
    'Alegria',
    'Amayco',
    'Zone I (Pob.)',
    'Zone II (Pob.)',
    'Zone III (Pob.)',
    'Zone IV (Pob.)',
    'Zone V (Pob.)',
    'Blumentritt',
    'Buenavista',
    'Caliban',
    'Canlandog',
    'Cansilayan',
    'Damsite',
    'Iglau-an',
    'Lopez Jaena',
    'Minoyan',
    'Pandanon',
    'San Miguel',
    'Santa Cruz',
    'Santa Rosa',
    'Salvacion',
    'Talotog'
];
var Pontevedra = [
    'Antipolo',
    'Barangay I (Poblacion)',
    'Barangay II (Poblacion)',
    'Barangay III (Poblacion)',
    'Buenavista Gibong',
    'Buenavista Rizal',
    'Burgos',
    'Cambarus',
    'Canroma',
    'General Malvar',
    'Gomez',
    'M. H. Del Pilar',
    'Mabini',
    'Miranda',
    'Pandan',
    'Recreo',
    'San Isidro',
    'San Juan',
    'Zamora'
];
var Pulupandan = [
    'Barangay Zone 1-A (Pob.)',
    'Barangay Zone 4-A (Pob.)',
    'Barangay Zone 1 (Pob.)',
    'Barangay Zone 2 (Pob.)',
    'Barangay Zone 3 (Pob.)',
    'Barangay Zone 4 (Pob.)',
    'Barangay Zone 5 (Pob.)',
    'Barangay Zone 6 (Pob.)',
    'Barangay Zone 7 (Pob.)',
    'Canjusa'
];
var DSB = [
    'Bago (Lalung)',
    'Bagong Silang (Marcelo)',
    'Bunga',
    'Igmaya-an',
    'Kumaliskis',
    'Pandanon',
    'Pinowayan (Prosperidad)'
];
var Sagay = [
    'Andres Bonifacio',
    'Bato',
    'Baviera',
    'Bulanon',
    'Campo Himoga-an',
    'Campo Santiago',
    'Colonia Divina',
    'Rafaela Barrera',
    'Fabrica',
    'General Luna',
    'Himoga-an Baybay',
    'Lopez Jaena',
    'Malubon',
    'Makiling',
    'Molocaboc',
    'Old Sagay',
    'Paraiso',
    'Plaridel',
    'Poblacion I (Barangay 1)',
    'Poblacion II (Barangay 2)',
    'Puey',
    'Rizal',
    'Taba-ao',
    'Tadlong',
    'Vito'
];
var SanCarlos = [
    'Bagonbon',
    'Buluangan',
    'Codcod',
    'Ermita (Sipaway)',
    'Guadalupe',
    'Nataban',
    'Palampas',
    'Barangay I (Poblacion)',
    'Barangay II (Poblacion)',
    'Barangay III (Poblacion)',
    'Barangay IV (Poblacion)',
    'Barangay V (Poblacion)',
    'Barangay VI (Poblacion)',
    'Prosperidad',
    'Punao',
    'Quezon',
    'Rizal',
    'San Juan (Sipaway)'
];
var SanErique = [
    'Bagonawa',
    'Baliwagan',
    'Batuan',
    'Guintorilan',
    'Nayon',
    'Poblacion',
    'Sibucao',
    'Tabao Baybay',
    'Tabao Rizal',
    'Tibsok'
];
var Silay = [
    'Barangay I (Poblacion)',
    'Barangay II (Poblacion)',
    'Barangay III (Poblacion)',
    'Barangay IV (Poblacion)',
    'Barangay V (Poblacion)',
    'Barangay VI (Poblacion)',
    'Eustaquio Lopez',
    'Guimbala-on',
    'Guinhalaran',
    'Kapitan Ramon',
    'Lantad',
    'Mambulac',
    'Rizal',
    'Bagtic',
    'Patag',
    'Balaring'
];
var Sipalay = [
    'Barangay 1 (Pob.)',
    'Barangay 2 (Pob.)',
    'Barangay 3 (Pob.)',
    'Barangay 4 (Pob.)',
    'Barangay 5 (Pob.)',
    'Cabadiangan',
    'Camindangan',
    'Canturay',
    'Cartagena',
    'Cayhagan',
    'Gil Montilla',
    'Mambaroto',
    'Manlucahoc',
    'Maricalum',
    'Nabulao',
    'Nauhang',
    'San Jose'
];
var Talisay = [
    'Bubog',
    'Cabatangan',
    'Zone 4-A (Poblacion)',
    'Zone 4 (Poblacion)',
    'Concepcion',
    'Dos Hermanas',
    'Efigenio Lizares',
    'Zone 7 (Poblacion)',
    'Zone 14-B (Poblacion)',
    'Zone 12-A (Poblacion)',
    'Zone 10 (Poblacion)',
    'Zone 5 (Poblacion)',
    'Zone 16 (Poblacion)',
    'Matab-ang',
    'Zone 9 (Poblacion)',
    'Zone 6 (Poblacion)',
    'Zone 14 (Poblacion)',
    'San Fernando',
    'Zone 15 (Poblacion)',
    'Zone 14-A (Poblacion)',
    'Zone 11 (Poblacion)',
    'Zone 8 (Poblacion)',
    'Zone 12 (Poblacion)',
    'Zone 1 (Poblacion)',
    'Zone 2 (Poblacion)',
    'Zone 3 (Poblacion)',
    'Katilingban'
];
var Toboso = [
    'Bandila',
    'Bug-ang',
    'General Luna',
    'Magticol',
    'Poblacion',
    'Salamanca',
    'San Isidro',
    'San Jose',
    'Tabun-ac'
];
var Valladolid = [
    'Alijis',
    'Ayungon',
    'Bagumbayan',
    'Batuan',
    'Bayabas',
    'Central Tabao',
    'Doldol',
    'Guintorilan',
    'Lacaron',
    'Mabini',
    'Pacol',
    'Palaka',
    'Paloma',
    'Poblacion',
    'Sagua Banua',
    'Tabao Proper'
];
var Victorias = [
    'Barangay I (Poblacion)',
    'Barangay II (Quezon; Pob.)',
    'Barangay III (Poblacion)',
    'Barangay IV (Poblacion)',
    'Barangay V (Poblacion)',
    'Barangay VI (Estrella Village/Salvacion; Pob.)',
    'Barangay VI-A (Boulevard/Villa Miranda/Sitio Cubay/Pasil)',
    'Barangay VII (Poblacion)',
    'Barangay VIII (Old Simboryo)',
    'Barangay IX (Daan Banwa)',
    'Barangay X (Estado)',
    'Barangay XI (Gawahon)',
    'Barangay XII',
    'Barangay XIII (Gloryville)',
    'Barangay XIV',
    'Barangay XV West Caticlan',
    'Barangay XV-A East Caticlan',
    'Barangay XVI',
    'Barangay XVI-A',
    'Barangay XVII',
    'Barangay XVIII',
    'Barangay XVIII-A (Florencia, Kubay, Golf)',
    'Barangay XIX',
    'Barangay XIX-A (Canetown Subdivision)',
    'Barangay XX',
    'Barangay XXI'
];




export { EBMagalona, Victorias, Valladolid, Toboso, Talisay, Sipalay, Silay, SanErique, SanCarlos, Sagay, DSB, Pulupandan, Pontevedra, Murcia, MoisisPaddilla, bacolodCity, citymunicipal, HimamaylanBrgy, BagoCity, Binalbagan, Calatrava, CadizCity, Candoni, Cauayan, Escalante, Hinigaran, Hinobaan, Ilog, Isabela, KabankalanCIty, LaCarlota, LaCastellana, Manapla };